"""IT: Alembic schema と seed（MySQL 必須。テスト設計書 1.3・1.4 #4・6 章）。

① upgrade head 後に P1 の 12 表がある
② `alembic check` 相当でモデルとの差分ゼロ
③ seed 後の件数（商品 31・バリエーション 186・system_settings 4 など）
④ tax_rate が文字列 "0.10" で取り出せる（DS-DEC-31）
⑤ V-STOCK0 / V-STOCK1 / P-UNPUB / P-ALL0
⑥ seed を 2 回呼んでも件数が変わらない（冪等・データ保護側）
"""

from __future__ import annotations

import asyncio

from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession, create_async_engine

from alembic import command
from app import seed_data
from app.models import P1_TABLES, Product, SystemSetting, Variant
from app.seed import count_rows, seed
from tests.integration.conftest import alembic_config


async def test_it_schema_01_upgrade_head_creates_12_tables(it_engine: AsyncEngine) -> None:
    async with it_engine.connect() as conn:
        tables = {row[0] for row in await conn.execute(text("SHOW TABLES"))}
        version = (await conn.execute(text("SELECT version_num FROM alembic_version"))).scalars()
        versions = list(version)
    assert P1_TABLES <= tables, f"欠けている表: {sorted(P1_TABLES - tables)}"
    assert "alembic_version" in tables
    assert len(versions) == 1


def test_it_schema_02_alembic_check_no_diff(migrated_schema: str) -> None:
    """モデル（Base.metadata）と DB の差分がゼロ。差分があれば AutogenerateDiffsDetected。"""
    try:
        command.check(alembic_config(migrated_schema))
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - 失敗時の説明用
        raise AssertionError(f"モデルと DB に差分があります: {exc}") from exc


async def test_it_seed_03_counts(seed_db: AsyncEngine) -> None:
    async with seed_db.connect() as conn:
        counts = await count_rows(conn)
    assert counts["products"] == seed_data.EXPECTED_PRODUCT_COUNT == 31
    assert counts["variants"] == seed_data.EXPECTED_VARIANT_COUNT == 186
    assert counts["system_settings"] == seed_data.EXPECTED_SYSTEM_SETTING_COUNT == 4
    assert counts["categories"] == seed_data.EXPECTED_CATEGORY_COUNT
    assert counts["product_images"] == seed_data.EXPECTED_IMAGE_COUNT
    assert counts["product_categories"] == seed_data.EXPECTED_PRODUCT_CATEGORY_COUNT


async def test_it_seed_04_tax_rate_is_string(seed_db: AsyncEngine) -> None:
    async with AsyncSession(seed_db) as session:
        row = (
            await session.execute(select(SystemSetting).where(SystemSetting.key == "tax_rate"))
        ).scalar_one()
        assert row.value == "0.10"
        assert isinstance(row.value, str), "tax_rate は JSON 文字列で保持する（DS-DEC-31）"
        others = {
            r.key: r.value
            for r in (await session.execute(select(SystemSetting))).scalars()
            if r.key != "tax_rate"
        }
    assert others == {
        "shipping_fee": 550,
        "free_shipping_threshold": 4990,
        "payment_timeout_minutes": 30,
    }


async def test_it_seed_05_test_data_markers(seed_db: AsyncEngine) -> None:
    async with AsyncSession(seed_db) as session:
        stock0 = (
            await session.execute(select(Variant).where(Variant.sku == seed_data.TEST_SKU_STOCK0))
        ).scalar_one()
        stock1 = (
            await session.execute(select(Variant).where(Variant.sku == seed_data.TEST_SKU_STOCK1))
        ).scalar_one()
        unpub = (
            await session.execute(
                select(Product).where(Product.name == seed_data.TEST_PRODUCT_NAME_UNPUB)
            )
        ).scalar_one()
        all0 = (
            await session.execute(
                select(Product).where(Product.name == seed_data.TEST_PRODUCT_NAME_ALL0)
            )
        ).scalar_one()
        all0_stocks = (
            (await session.execute(select(Variant.stock).where(Variant.product_id == all0.id)))
            .scalars()
            .all()
        )
        # 在庫 0 / 1 のバリエーションは公開商品に属する
        stock0_product = await session.get(Product, stock0.product_id)
        stock1_product = await session.get(Product, stock1.product_id)

    assert stock0.stock == 0
    assert stock1.stock == 1
    assert stock0_product is not None and stock0_product.published is True
    assert stock1_product is not None and stock1_product.published is True
    assert unpub.published is False
    assert all0.published is True
    assert len(all0_stocks) == 6 and all(s == 0 for s in all0_stocks)


async def test_it_seed_06_idempotent_second_call_is_noop(seed_db: AsyncEngine) -> None:
    async with seed_db.connect() as conn:
        before = await count_rows(conn)
    result = await seed(seed_db, reset=False)
    async with seed_db.connect() as conn:
        after = await count_rows(conn)
    assert result.skipped is True
    assert after == before


async def test_it_schema_07_categories_kind_column_and_seed(seed_db: AsyncEngine) -> None:
    """categories.kind は VARCHAR(32)・NULL 可。親は NULL、子は slug から性別接頭辞を除いた値。"""
    async with seed_db.connect() as conn:
        col = (
            await conn.execute(
                text(
                    "SELECT DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE "
                    "FROM information_schema.COLUMNS "
                    "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'categories' "
                    "AND COLUMN_NAME = 'kind'"
                )
            )
        ).one()
        rows = (await conn.execute(text("SELECT slug, parent_id, kind FROM categories"))).all()
    assert (col[0], col[1], col[2]) == ("varchar", 32, "YES")
    expected = {c.slug: c.kind for c in seed_data.CATEGORIES}
    assert {r[0]: r[2] for r in rows} == expected
    assert all(r[2] is None for r in rows if r[1] is None), "親（性別）の kind は NULL"
    assert {r[2] for r in rows if r[1] is not None} == {
        "tops",
        "bottoms",
        "outer",
        "dresses",
        "inner-goods",
    }


def test_it_schema_08_kind_migration_backfills_existing_children(migrated_schema: str) -> None:
    """kind 追加前（371a338f4624）の categories に対し upgrade が既存の子へ kind を入れ、
    downgrade が列を削除する。終わったら必ず head に戻し、categories を空にする。"""
    cfg = alembic_config(migrated_schema)
    old_rev = "371a338f4624"  # pragma: allowlist secret（1 つ前の版）

    async def _run(statements: list[str]) -> list[tuple]:
        engine = create_async_engine(migrated_schema)
        try:
            async with engine.begin() as conn:
                out: list[tuple] = []
                for sql in statements:
                    result = await conn.execute(text(sql))
                    if result.returns_rows:
                        out = [tuple(r) for r in result.all()]
                return out
        finally:
            await engine.dispose()

    insert = (
        "INSERT INTO categories (name, slug, parent_id, gender, sort_order) VALUES "
        "('レディース', 'women', NULL, 'women', 0), "
        "('キッズ・ティーン', 'kids-teen', NULL, 'kids_teen', 2)"
    )
    insert_children = (
        "INSERT INTO categories (name, slug, parent_id, gender, sort_order) "
        "SELECT 'トップス', 'women-tops', id, 'women', 0 FROM categories WHERE slug = 'women' "
        "UNION ALL "
        "SELECT 'インナー・雑貨', 'kids-teen-inner-goods', id, 'kids_teen', 3 "
        "FROM categories WHERE slug = 'kids-teen'"
    )
    try:
        asyncio.run(
            _run(["DELETE FROM categories WHERE parent_id IS NOT NULL", "DELETE FROM categories"])
        )
        command.downgrade(cfg, old_rev)
        cols = asyncio.run(
            _run(
                [
                    "SELECT COUNT(*) FROM information_schema.COLUMNS "
                    "WHERE TABLE_SCHEMA = DATABASE() "
                    "AND TABLE_NAME = 'categories' AND COLUMN_NAME = 'kind'"
                ]
            )
        )
        assert cols == [(0,)], "downgrade で kind 列が消える"
        asyncio.run(_run([insert, insert_children]))

        command.upgrade(cfg, "head")
        rows = asyncio.run(_run(["SELECT slug, kind FROM categories ORDER BY id"]))
        assert rows == [
            ("women", None),
            ("kids-teen", None),
            ("women-tops", "tops"),
            ("kids-teen-inner-goods", "inner-goods"),
        ]
    finally:
        command.upgrade(cfg, "head")
        asyncio.run(
            _run(["DELETE FROM categories WHERE parent_id IS NOT NULL", "DELETE FROM categories"])
        )
