"""IT: Alembic schema と seed（MySQL 必須。テスト設計書 1.3・1.4 #4・6 章）。

① upgrade head 後に P1 の 12 表がある
② `alembic check` 相当でモデルとの差分ゼロ
③ seed 後の件数（商品 30・バリエーション 180・system_settings 4 など）
④ tax_rate が文字列 "0.10" で取り出せる（DS-DEC-31）
⑤ V-STOCK0 / V-STOCK1 / P-UNPUB / P-ALL0
⑥ seed を 2 回呼んでも件数が変わらない（冪等・データ保護側）
"""

from __future__ import annotations

from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession

from alembic import command
from app import seed_data
from app.models import P1_TABLES, Product, SystemSetting, Variant
from app.seed import count_rows, seed
from tests.integration.conftest import alembic_config


async def test_it_schema_01_upgrade_head_creates_12_tables(it_engine: AsyncEngine) -> None:
    async with it_engine.connect() as conn:
        tables = {row[0] for row in await conn.execute(text("SHOW TABLES"))}
        version = (await conn.execute(text("SELECT version_num FROM alembic_version"))).scalars()
        versions = list(version)
    assert P1_TABLES <= tables, f"欠けている表: {sorted(P1_TABLES - tables)}"
    assert "alembic_version" in tables
    assert len(versions) == 1


def test_it_schema_02_alembic_check_no_diff(migrated_schema: str) -> None:
    """モデル（Base.metadata）と DB の差分がゼロ。差分があれば AutogenerateDiffsDetected。"""
    try:
        command.check(alembic_config(migrated_schema))
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - 失敗時の説明用
        raise AssertionError(f"モデルと DB に差分があります: {exc}") from exc


async def test_it_seed_03_counts(seed_db: AsyncEngine) -> None:
    async with seed_db.connect() as conn:
        counts = await count_rows(conn)
    assert counts["products"] == seed_data.EXPECTED_PRODUCT_COUNT == 30
    assert counts["variants"] == seed_data.EXPECTED_VARIANT_COUNT == 180
    assert counts["system_settings"] == seed_data.EXPECTED_SYSTEM_SETTING_COUNT == 4
    assert counts["categories"] == seed_data.EXPECTED_CATEGORY_COUNT
    assert counts["product_images"] == seed_data.EXPECTED_IMAGE_COUNT
    assert counts["product_categories"] == seed_data.EXPECTED_PRODUCT_CATEGORY_COUNT


async def test_it_seed_04_tax_rate_is_string(seed_db: AsyncEngine) -> None:
    async with AsyncSession(seed_db) as session:
        row = (
            await session.execute(select(SystemSetting).where(SystemSetting.key == "tax_rate"))
        ).scalar_one()
        assert row.value == "0.10"
        assert isinstance(row.value, str), "tax_rate は JSON 文字列で保持する（DS-DEC-31）"
        others = {
            r.key: r.value
            for r in (await session.execute(select(SystemSetting))).scalars()
            if r.key != "tax_rate"
        }
    assert others == {
        "shipping_fee": 550,
        "free_shipping_threshold": 4990,
        "payment_timeout_minutes": 30,
    }


async def test_it_seed_05_test_data_markers(seed_db: AsyncEngine) -> None:
    async with AsyncSession(seed_db) as session:
        stock0 = (
            await session.execute(select(Variant).where(Variant.sku == seed_data.TEST_SKU_STOCK0))
        ).scalar_one()
        stock1 = (
            await session.execute(select(Variant).where(Variant.sku == seed_data.TEST_SKU_STOCK1))
        ).scalar_one()
        unpub = (
            await session.execute(
                select(Product).where(Product.name == seed_data.TEST_PRODUCT_NAME_UNPUB)
            )
        ).scalar_one()
        all0 = (
            await session.execute(
                select(Product).where(Product.name == seed_data.TEST_PRODUCT_NAME_ALL0)
            )
        ).scalar_one()
        all0_stocks = (
            (await session.execute(select(Variant.stock).where(Variant.product_id == all0.id)))
            .scalars()
            .all()
        )
        # 在庫 0 / 1 のバリエーションは公開商品に属する
        stock0_product = await session.get(Product, stock0.product_id)
        stock1_product = await session.get(Product, stock1.product_id)

    assert stock0.stock == 0
    assert stock1.stock == 1
    assert stock0_product is not None and stock0_product.published is True
    assert stock1_product is not None and stock1_product.published is True
    assert unpub.published is False
    assert all0.published is True
    assert len(all0_stocks) == 6 and all(s == 0 for s in all0_stocks)


async def test_it_seed_06_idempotent_second_call_is_noop(seed_db: AsyncEngine) -> None:
    async with seed_db.connect() as conn:
        before = await count_rows(conn)
    result = await seed(seed_db, reset=False)
    async with seed_db.connect() as conn:
        after = await count_rows(conn)
    assert result.skipped is True
    assert after == before
